extensions:
  commerce/backend-ui/1:
    operations:
      view:
        - type: web
          impl: index.html
    actions: actions
    web: web-src
    runtimeManifest:
      packages:
        SampleExtension:
          license: Apache-2.0
          actions:
            commerce-rest-get:
              function: actions/commerce/index.js
              web: 'yes'
              runtime: 'nodejs:16'
              inputs:
                LOG_LEVEL: debug
                COMMERCE_BASE_URL: $COMMERCE_BASE_URL
                COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
                COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
                COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
                COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
              annotations:
                require-adobe-auth: false
                final: true
            get-order-grid-columns:
              function: actions/data/orderGridColumns.js
              web: 'yes'
              runtime: 'nodejs:16'
              inputs:
                LOG_LEVEL: debug
              annotations:
                require-adobe-auth: false
                final: true
            get-product-grid-columns:
              function: actions/data/productGridColumns.js
              web: 'yes'
              runtime: 'nodejs:16'
              inputs:
                LOG_LEVEL: debug
              annotations:
                require-adobe-auth: false
                final: true
