extensions:
  commerce/backend-ui/1:
    operations:
      view:
        - type: web
          impl: index.html
    web: web-src
    runtimeManifest:
      packages:
        CustomViewButton:
          license: Apache-2.0
