application:
  hooks:
    pre-app-build: ./hooks/pre-app-build.js
  actions: actions
  runtimeManifest:
    packages:
      commerce-checkout-starter-kit:
        license: Apache-2.0
        actions:
          info:
            function: actions/commerce-checkout-starter-kit-info/index.js
            web: 'yes'
            runtime: nodejs:22
            annotations:
              require-adobe-auth: true
              final: true
              code-download: false
      custom-shipping:
        license: Apache-2.0
        actions:
          shipping-methods:
            function: actions/shipping-methods/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              COMMERCE_WEBHOOKS_PUBLIC_KEY: $COMMERCE_WEBHOOKS_PUBLIC_KEY
              ENABLE_TELEMETRY: true
            annotations:
              require-adobe-auth: false
              raw-http: true
              final: true
              code-download: false
extensions:
  commerce/backend-ui/1:
    $include: commerce-backend-ui-1/ext.config.yaml
productDependencies:
  - code: COMMC
    minVersion: 2.4.5
    maxVersion: 3.0.0
