// This file has been auto-generated by `@adobe/aio-commerce-lib-app`
// Do not modify this file directly

import { configRuntimeAction } from "@adobe/aio-commerce-lib-app/actions/config";

import config from "#app.commerce.config";

const businessConfig = /** @type {NonNullable<typeof config.businessConfig>} */ (
  config.businessConfig
);
const configSchema = /** @type {NonNullable<typeof businessConfig.schema>} */ (
  businessConfig.schema
);
const args = { configSchema };
export const main = configRuntimeAction(args);
