// This file has been auto-generated by `@adobe/aio-commerce-lib-app`
// Do not modify this file directly

import { configRuntimeAction } from "@adobe/aio-commerce-lib-app/actions/config";

import config from "#app.commerce.config";

const args = { configSchema: config.businessConfig.schema };
export const main = configRuntimeAction(args);
