// This file has been auto-generated by `@adobe/aio-commerce-lib-app`
// Do not modify this file directly

import { scopeTreeRuntimeAction } from "@adobe/aio-commerce-lib-app/actions/scope-tree";

export const main = scopeTreeRuntimeAction;
