import { useCallback, useState } from "react";

const CONFIG_ACTION_KEY = "DeliveryEstimates/delivery-estimates-config";

function getActionUrl() {
  // config.json is generated by the App Builder CLI at build time
  // eslint-disable-next-line node/no-missing-require,node/no-unpublished-require
  const actions = require("../config.json");
  return actions[CONFIG_ACTION_KEY];
}

async function fetchConfig({ actionUrl, imsToken, imsOrgId, method, body }) {
  const res = await fetch(actionUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-gw-ims-org-id": imsOrgId,
      authorization: `Bearer ${imsToken}`,
    },
    body: JSON.stringify({ method, ...body }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`HTTP ${res.status}: ${text}`);
  }

  return res.json();
}

export function useDeliveryConfig({ imsToken, imsOrgId }) {
  const [config, setConfig] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState(null);

  const loadConfig = useCallback(async () => {
    if (!imsToken) {
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const actionUrl = getActionUrl();
      const result = await fetchConfig({
        actionUrl,
        imsToken,
        imsOrgId,
        method: "GET",
      });

      if (result?.error) {
        throw new Error(
          result.error?.body?.error || JSON.stringify(result.error),
        );
      }

      setConfig(result);
    } catch (e) {
      console.error("Error loading delivery config:", e);
      setError(e.message);
    } finally {
      setIsLoading(false);
    }
  }, [imsToken, imsOrgId]);

  const saveConfig = useCallback(
    async (payload) => {
      if (!imsToken) {
        return;
      }

      setIsSaving(true);
      setError(null);

      try {
        const actionUrl = getActionUrl();
        const result = await fetchConfig({
          actionUrl,
          imsToken,
          imsOrgId,
          method: "PUT",
          body: payload,
        });

        if (result?.error) {
          throw new Error(
            result.error?.body?.error || JSON.stringify(result.error),
          );
        }

        setConfig(result);
        return result;
      } catch (e) {
        console.error("Error saving delivery config:", e);
        setError(e.message);
        throw e;
      } finally {
        setIsSaving(false);
      }
    },
    [imsToken, imsOrgId],
  );

  return { config, isLoading, error, loadConfig, saveConfig, isSaving };
}
