// This file has been auto-generated by `@adobe/aio-commerce-lib-app`
// Do not modify this file directly

import { installationRuntimeAction } from "@adobe/aio-commerce-lib-app/actions/installation"
import appConfig from "#app.commerce.config";

import * as customScript0 from "../../../../../scripts/setup-database.js";

import { defineCustomScriptsLoader } from "@adobe/aio-commerce-lib-app/actions/installation";

/**
 * Loads custom installation scripts defined in the manifest
 */
export const customScriptsLoader = defineCustomScriptsLoader((appConfig, logger) => {
  const customSteps = appConfig.installation?.customInstallationSteps ?? [];

  if (customSteps.length === 0) {
    logger.debug("No custom installation scripts configured");
    return {};
  }

  try {
    const loadedScripts = {
      "./scripts/setup-database.js": customScript0,
    };

    logger.debug(`Loaded ${Object.keys(loadedScripts).length} custom installation script(s)`);
    return loadedScripts;
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    logger.error(`Failed to load custom installation scripts: ${reason}`);
    throw new Error(`Failed to load custom installation scripts: ${reason}`, {
      cause: error,
    });
  }
});

const args = { appConfig, customScriptsLoader };
export const main = installationRuntimeAction(args);
